

#!/bin/bash

set -e

TARGET_ENV=$1

# Check to see if first arg is an empty string, and if so, then default test environment to 'SIT'
if [ -z "$1" ]
  then
    echo "Environment Check :: No test environment specified"
    echo "Environment Check :: Defaulting test environment to SIT..."
    TARGET_ENV="sit"
  else
    echo "Environment Check :: Test environment specified :: $TARGET_ENV"
fi

# Clean up anything that could be cached (i.e. - .js files)
echo "Clean Slate :: Working to remove any locally cached files..."
npx rimraf "./libs/pricing-engine/e2e/dist" # using 'npx' in case user doesn't have 'rimraf' installed globally
echo "Clean Slate :: Locally cached files removed successfully"

# Clean up reporting related to previous runs to avoid unnecessary duplicates
echo "Clean Slate :: Working to remove reporting files generated by previous test runs..."
npx rimraf "./libs/pricing-engine/e2e/reporting/" # using 'npx' in case user doesn't have 'rimraf' installed globally
echo "Clean Slate :: All reporting related to previous test runs removed successfully"

# Run the Typescript compiler to compile our .ts files into .js files
cd "./libs/pricing-engine/e2e/"
../../../node_modules/typescript/bin/tsc

# Run our tests
cd "../../.."
./node_modules/protractor/bin/protractor ./libs/pricing-engine/e2e/protractor.conf.js --disableChecks --targetEnv=$TARGET_ENV
