import { DataComponent } from "../../model/data-component";

export const DEFAULT_PIPELINE_COLUMN_METADATA: DataComponent[] = [
  {
    activeInd: true,
    dataMappingName: "opportunityId",
    dataValueEditableInd: false,
    description: "This is the description for the oppurtunity I.D.",
    displayOrderNumber: 0,
    name: "Opportunity",
    dataValueType: "string",
    shortName: "Opportunity Id",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "maxUPB",
    dataValueEditableInd: true,
    description: "This is the description for the max UPB.",
    displayOrderNumber: 1,
    name: "Max UPB",
    dataValueType: "string",
    shortName: "Max UPB",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "submitDateTime",
    dataValueEditableInd: false,
    description: "This is the description for the claimedBy",
    displayOrderNumber: 4,
    name: "Submitted",
    dataValueType: "string",
    shortName: "Date Submitted",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "propertyName",
    dataValueEditableInd: true,
    description: "This is the description for the Property Name",
    displayOrderNumber: 5,
    name: "Property",
    dataValueType: "string",
    shortName: "Property",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "borrower",
    dataValueEditableInd: true,
    description: "This is the description for the borrower",
    displayOrderNumber: 6,
    name: "Borrower",
    dataValueType: "string",
    shortName: "Borrower",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "producer",
    dataValueEditableInd: false,
    description: "This is the description for the producer",
    displayOrderNumber: 7,
    name: "Producer",
    dataValueType: "string",
    shortName: "Producer",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "region",
    dataValueEditableInd: false,
    description: "This is the description for the region",
    displayOrderNumber: 8,
    name: "Region",
    dataValueType: "string",
    shortName: "Region",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "claimedBy",
    dataValueEditableInd: false,
    description: "This is the description for the claimedBy",
    displayOrderNumber: 2,
    name: "Claimed",
    dataValueType: "string",
    shortName: "Claimed",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "quoteCount",
    dataValueEditableInd: false,
    description: "This is the description for the region",
    displayOrderNumber: 8,
    name: "",
    dataValueType: "string",
    shortName: "Type",
    componentType: "pipeline",
    sectionName: "",
  },
];

export const AwaitingApprovalData: DataComponent[] = [
  {
    activeInd: true,
    dataMappingName: "opportunityId",
    dataValueEditableInd: false,
    description: "This is the description for the oppurtunity I.D.",
    displayOrderNumber: 0,
    name: "Opportunity",
    dataValueType: "string",
    shortName: "Opportunity Id",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "maxUPB",
    dataValueEditableInd: true,
    description: "This is the description for the max UPB.",
    displayOrderNumber: 1,
    name: "Max UPB",
    dataValueType: "string",
    shortName: "Max UPB",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "submitDateTime",
    dataValueEditableInd: false,
    description: "This is the description for the claimedBy",
    displayOrderNumber: 4,
    name: "Submitted",
    dataValueType: "string",
    shortName: "Date Submitted",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "propertyName",
    dataValueEditableInd: true,
    description: "This is the description for the Property Name",
    displayOrderNumber: 5,
    name: "Property",
    dataValueType: "string",
    shortName: "Property",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "borrower",
    dataValueEditableInd: true,
    description: "This is the description for the borrower",
    displayOrderNumber: 6,
    name: "Borrower",
    dataValueType: "string",
    shortName: "Borrower",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "producer",
    dataValueEditableInd: false,
    description: "This is the description for the producer",
    displayOrderNumber: 7,
    name: "Producer",
    dataValueType: "string",
    shortName: "Producer",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "region",
    dataValueEditableInd: false,
    description: "This is the description for the region",
    displayOrderNumber: 8,
    name: "Region",
    dataValueType: "string",
    shortName: "Region",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "approvalHold",
    dataValueEditableInd: false,
    description: "This is the description for the claimedBy",
    displayOrderNumber: 10,
    name: "Hold",
    dataValueType: "string",
    shortName: "Approval Hold",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "claimedBy",
    dataValueEditableInd: false,
    description: "This is the description for the claimedBy",
    displayOrderNumber: 2,
    name: "Claimed",
    dataValueType: "string",
    shortName: "Claimed",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "quoteCount",
    dataValueEditableInd: false,
    description: "This is the description for the region",
    displayOrderNumber: 8,
    name: "",
    dataValueType: "string",
    shortName: "Type",
    componentType: "pipeline",
    sectionName: "",
  },
];

export const QUOTE_RESULTS_COLUMN_METADATA: DataComponent[] = [
  {
    activeInd: true,
    componentType: "quoteResults",
    dataMappingName: "quoteId",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the description for the QuoteId column",
    displayOrderNumber: 0,
    filterableInd: false,
    filterListOptionInd: false,
    name: "Quote",
    sectionName: "",
    shortName: "Quote",
    sortableInd: false,
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "opportunityUpbAmt",
    dataValueEditableInd: false,
    description: "This is the description for the UPB",
    displayOrderNumber: 2,
    name: "UPB",
    dataValueType: "string",
    shortName: "upb",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "statusType",
    dataValueEditableInd: false,
    description: "This is the description for the quote status",
    displayOrderNumber: 0,
    name: "Quote Status",
    dataValueType: "string",
    shortName: "Quote Status",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "ltvValue",
    dataValueEditableInd: true,
    description: "This is the description for the LTV.",
    displayOrderNumber: 1,
    name: "LTV",
    dataValueType: "string",
    shortName: "LTV",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "dcrPricingMnrValue",
    dataValueEditableInd: false,
    description: "This is the description for the DCR",
    displayOrderNumber: 4,
    name: "DCR/MNR",
    dataValueType: "string",
    shortName: "DCR",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "prePayValue",
    dataValueEditableInd: true,
    description: "This is the description for the Property Name",
    displayOrderNumber: 5,
    name: "Prepay",
    dataValueType: "string",
    shortName: "Prepay",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "quoteType",
    dataValueEditableInd: true,
    description: "This is the description for the Product Type",
    displayOrderNumber: 6,
    name: "Product Type",
    dataValueType: "string",
    shortName: "Product Type",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "priorityIndicator",
    dataValueEditableInd: false,
    description: "This is the description for the priority",
    displayOrderNumber: 7,
    name: "Priority",
    dataValueType: "string",
    shortName: "Priority",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "submitDateTime",
    dataValueEditableInd: false,
    description: "This is the description for the date",
    displayOrderNumber: 8,
    name: "Submitted",
    dataValueType: "string",
    shortName: "Submitted",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "poolName",
    dataValueEditableInd: false,
    description: "This is the description for the poolName",
    displayOrderNumber: 10,
    name: "Pool",
    dataValueType: "string",
    shortName: "Pool",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
];

export const QUOTE_RESULTS_EXTENSION_COLUMN_METADATA: DataComponent[] = [
  {
    activeInd: true,
    componentType: "quoteResults",
    dataMappingName: "quoteId",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the description for the QuoteId column",
    displayOrderNumber: 0,
    filterableInd: false,
    filterListOptionInd: false,
    name: "Quote ID",
    sectionName: "",
    shortName: "Quote ID",
    sortableInd: false,
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "opportunityUpbAmt",
    dataValueEditableInd: false,
    description: "This is the description for the UPB",
    displayOrderNumber: 2,
    name: "UPB",
    dataValueType: "string",
    shortName: "upb",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "statusType",
    dataValueEditableInd: false,
    description: "This is the description for the quote status",
    displayOrderNumber: 0,
    name: "Quote Status",
    dataValueType: "string",
    shortName: "Quote Status",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "ltvValue",
    dataValueEditableInd: true,
    description: "This is the description for the LTV.",
    displayOrderNumber: 1,
    name: "LTV",
    dataValueType: "string",
    shortName: "LTV",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "dcrPricingMnrValue",
    dataValueEditableInd: false,
    description: "This is the description for the DCR",
    displayOrderNumber: 4,
    name: "DCR/MNR ",
    dataValueType: "string",
    shortName: "DCR",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "prePayValue",
    dataValueEditableInd: true,
    description: "This is the description for the Property Name",
    displayOrderNumber: 5,
    name: "Prepay",
    dataValueType: "string",
    shortName: "Prepay",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "quoteType",
    dataValueEditableInd: true,
    description: "This is the description for the Product Type",
    displayOrderNumber: 6,
    name: "Product Type",
    dataValueType: "string",
    shortName: "Product Type",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "priorityIndicator",
    dataValueEditableInd: false,
    description: "This is the description for the priority",
    displayOrderNumber: 7,
    name: "Priority",
    dataValueType: "string",
    shortName: "Priority",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "submitDateTime",
    dataValueEditableInd: false,
    description: "This is the description for the date",
    displayOrderNumber: 8,
    name: "Submitted",
    dataValueType: "string",
    shortName: "Submitted",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    componentType: "quoteResults",
    dataMappingName: "extensionType",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the description for the extension Type column",
    displayOrderNumber: 0,
    filterableInd: false,
    filterListOptionInd: false,
    name: "Extension Type",
    sectionName: "",
    shortName: "Extension Type",
    sortableInd: false,
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "poolName",
    dataValueEditableInd: false,
    description: "This is the description for the poolName",
    displayOrderNumber: 10,
    name: "Pool",
    dataValueType: "string",
    shortName: "Pool",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
];

export const QUOTE_RESULTS_APPROVAL_COLUMN_METADATA: DataComponent[] = [
  {
    activeInd: true,
    componentType: "quoteResults",
    dataMappingName: "quoteId",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the description for the QuoteId column",
    displayOrderNumber: 0,
    filterableInd: false,
    filterListOptionInd: false,
    name: "Quote ID",
    sectionName: "",
    shortName: "Quote ID",
    sortableInd: false,
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "opportunityUpbAmt",
    dataValueEditableInd: false,
    description: "This is the description for the UPB",
    displayOrderNumber: 2,
    name: "UPB",
    dataValueType: "string",
    shortName: "upb",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "statusType",
    dataValueEditableInd: false,
    description: "This is the description for the quote status",
    displayOrderNumber: 0,
    name: "Quote Status",
    dataValueType: "string",
    shortName: "Quote Status",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "ltvValue",
    dataValueEditableInd: true,
    description: "This is the description for the LTV.",
    displayOrderNumber: 1,
    name: "LTV",
    dataValueType: "string",
    shortName: "LTV",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "dcrPricingMnrValue",
    dataValueEditableInd: false,
    description: "This is the description for the DCR",
    displayOrderNumber: 4,
    name: "DCR/MNR ",
    dataValueType: "string",
    shortName: "DCR",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "prePayValue",
    dataValueEditableInd: true,
    description: "This is the description for the Property Name",
    displayOrderNumber: 5,
    name: "Prepay",
    dataValueType: "string",
    shortName: "Prepay",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "quoteType",
    dataValueEditableInd: true,
    description: "This is the description for the Product Type",
    displayOrderNumber: 6,
    name: "Product Type",
    dataValueType: "string",
    shortName: "Product Type",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "priorityIndicator",
    dataValueEditableInd: false,
    description: "This is the description for the priority",
    displayOrderNumber: 7,
    name: "Priority",
    dataValueType: "string",
    shortName: "Priority",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "submitDateTime",
    dataValueEditableInd: false,
    description: "This is the description for the date",
    displayOrderNumber: 8,
    name: "Submitted",
    dataValueType: "string",
    shortName: "Submitted",
    value: "",
    componentType: "quoteResults",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "approvalHold",
    dataValueEditableInd: false,
    description: "This is the description for the Approval hold",
    displayOrderNumber: 10,
    name: "Approval Hold",
    dataValueType: "string",
    shortName: "Approval Hold",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
  {
    activeInd: true,
    dataMappingName: "poolName",
    dataValueEditableInd: false,
    description: "This is the description for the poolName",
    displayOrderNumber: 10,
    name: "Pool",
    dataValueType: "string",
    shortName: "Pool",
    value: "",
    componentType: "pipeline",
    filterableInd: true,
    filterListOptionInd: false,
    sectionName: "",
    sortableInd: true,
  },
];

export const OVERVIEW_METADATA: DataComponent[] = [
  {
    activeInd: true,
    dataMappingName: "unclaimedQuotes",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Unclaimed Quotes",
    displayOrderNumber: 0,
    name: "Unclaimed Quotes",
    sectionName: "new",
    shortName: "Unclaimed Qoutes",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "unapprovedQuotes",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Unapproved Quotes",
    displayOrderNumber: 1,
    name: "Unapproved Quotes",
    sectionName: "new",
    shortName: "Unapproved Quotes",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "highPriorityQuotes",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Priority Quotes",
    displayOrderNumber: 2,
    name: "Priority Quotes",
    sectionName: "new",
    shortName: "highPriorityQuotes",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "highPriorityOpportunities",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is  Priority Opportunities",
    displayOrderNumber: 3,
    name: "Priority Opportunities",
    sectionName: "new",
    shortName: "High Priority Opportunities",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "quotesGreaterThanFiftyMillion",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Quotes Greater Than FiftyMillion",
    displayOrderNumber: 4,
    name: "Quotes >50M",
    sectionName: "new",
    shortName: "Quote >50",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "opportunitiesGreaterThanFiftyMillion",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Opportunities Greater Than Fifty Million",
    displayOrderNumber: 5,
    name: "Opportunities >50M",
    sectionName: "new",
    shortName: "Opportunities >50",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "opportunitiesCount",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Opportunities Count",
    displayOrderNumber: 6,
    name: "Opportunities",
    sectionName: "new",
    shortName: "Opportunities",
    value: "",
  },
  {
    activeInd: true,
    dataMappingName: "quotesCount",
    dataValueEditableInd: false,
    dataValueType: "string",
    description: "This is the Quotes count",
    displayOrderNumber: 7,
    name: "Quotes",
    sectionName: "new",
    shortName: "Quotes",
    value: "",
  },
];
